# Generated by Django 3.2.4 on 2021-06-29 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('año', models.DateField()),
                ('genero', models.CharField(choices=[['Metal', 'METAL'], ['Rock', 'ROCK'], ['Clasica', 'CLASICA'], ['Salsa', 'SALSA'], ['Pop', 'POP']], max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
