# Generated by Django 3.2.4 on 2021-06-28 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banda_sonora', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=200)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('genero_pelicula', models.CharField(choices=[['TERROR', 'TERROR'], ['COMEDIA', 'COMEDIA'], ['DRAMA', 'DRAMA'], ['INFANTIL', 'INFANTIL'], ['ROMANTICA', 'ROMANTICA']], max_length=100)),
                ('clasificacion', models.CharField(choices=[['A', 'A'], ['B', 'B'], ['C', 'C']], max_length=1)),
                ('director_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='peliculas.director')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='banda_sonora.musica')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='peliculas.pelicula')),
            ],
        ),
    ]
