# Generated by Django 3.2.4 on 2021-06-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles',
            name='costo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
