# Generated by Django 3.2.4 on 2021-06-27 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banda_sonora', '0001_initial'),
        ('peliculas', '0002_alter_detalles_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles',
            name='musica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='banda_sonora.musica'),
        ),
        migrations.AlterField(
            model_name='detalles',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='peliculas.pelicula'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director_pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='peliculas.director'),
        ),
    ]
